### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [3]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [3]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - * torch.from_numpy(x) / x.numpy()


In [6]:
# Example 1 - ### tensor和array 互相轉換
### your code ###
a=torch.randn((2,3,4))
print('a:',a.shape)
b=a.numpy()
print('b:',b.shape)
c=torch.from_numpy(b)
print('c:',c.shape)
d = np.random.rand(2,2,3,3)
print('d:',d.shape)
e=torch.from_numpy(d)
print('e:',e.shape)


a: torch.Size([2, 3, 4])
b: (2, 3, 4)
c: torch.Size([2, 3, 4])
d: (2, 2, 3, 3)
e: torch.Size([2, 2, 3, 3])


In [21]:
# Example 2 - 
# 嘗試以torch.randint設立tensor和以numpy.random.randint設立numpy, 再以tensor.numpy()和torch.from_numpy來互相轉換
### your code ###
a=torch.randint(low=0, high=10, size=(3,4))
print(a)
print('a:',a.shape,a.dtype)
print('-------')
b=np.random.randint(low=0,high=5,size=(2,4))
print(b)
print('b:',b.shape,d.dtype)

c=a.numpy()
print('c:',c.shape, c.dtype)
d=torch.from_numpy(b)
print('d:',d.shape,d.dtype)

e=torch.tensor(b)
print('e:',e.shape,e.dtype)

tensor([[0, 3, 2, 7],
        [9, 9, 4, 0],
        [9, 3, 4, 4]])
a: torch.Size([3, 4]) torch.int64
-------
[[4 4 0 1]
 [3 3 1 4]]
b: (2, 4) torch.int32
c: (3, 4) int64
d: torch.Size([2, 4]) torch.int32
e: torch.Size([2, 4]) torch.int32


### Function 2 - torch.unsqueeze() / torch.squeeze()


In [47]:
# Example 1 - ### unsqueeze 在指定位置增加維度(僅增加1維度)   squeeze()壓縮(除去)1維度的地方
### your code ### squeeze() 對數據維度進行壓縮，去掉維度數為1的維度
a=torch.randint(low=0,high=10,size=(4,3,7))
print(a,a.shape)
print(' ')
g=torch.unsqueeze(a,dim=2)
print(g,g.shape)
print('  ')

h=torch.squeeze(g)
print(h,h.shape)

tensor([[[4, 4, 5, 6, 5, 9, 5],
         [8, 0, 2, 9, 8, 9, 8],
         [5, 7, 0, 9, 6, 1, 4]],

        [[8, 0, 3, 3, 4, 6, 7],
         [5, 2, 1, 6, 3, 3, 7],
         [8, 8, 4, 1, 2, 9, 3]],

        [[5, 6, 9, 4, 0, 6, 7],
         [0, 1, 5, 1, 2, 4, 4],
         [1, 9, 9, 4, 9, 8, 2]],

        [[6, 2, 6, 6, 2, 6, 2],
         [0, 8, 3, 5, 9, 0, 5],
         [1, 4, 4, 5, 2, 5, 5]]]) torch.Size([4, 3, 7])
 
tensor([[[[4, 4, 5, 6, 5, 9, 5]],

         [[8, 0, 2, 9, 8, 9, 8]],

         [[5, 7, 0, 9, 6, 1, 4]]],


        [[[8, 0, 3, 3, 4, 6, 7]],

         [[5, 2, 1, 6, 3, 3, 7]],

         [[8, 8, 4, 1, 2, 9, 3]]],


        [[[5, 6, 9, 4, 0, 6, 7]],

         [[0, 1, 5, 1, 2, 4, 4]],

         [[1, 9, 9, 4, 9, 8, 2]]],


        [[[6, 2, 6, 6, 2, 6, 2]],

         [[0, 8, 3, 5, 9, 0, 5]],

         [[1, 4, 4, 5, 2, 5, 5]]]]) torch.Size([4, 3, 1, 7])
  
tensor([[[4, 4, 5, 6, 5, 9, 5],
         [8, 0, 2, 9, 8, 9, 8],
         [5, 7, 0, 9, 6, 1, 4]],

        [[8, 0, 3, 3, 4, 6, 7],

In [53]:
# Example 2 - ### your explanation ###
### your code ###
a=torch.randn(1,3)#原始
print(a)
print("a:",a,a.shape)
b=torch.unsqueeze(a,1) #在a中位置為1的地方加上維數為1的維度
print("b:",b,b.shape)
c=a.unsqueeze(0) #在a中指定位置0加上一個維數為1的維度
print("c:",c,c.shape)
f=torch.randn(3)
print("f:",f,f.shape)
g=f.unsqueeze(0)
print("g:",g,g.shape)

tensor([[ 1.0161,  1.2925, -1.5285]])
a: tensor([[ 1.0161,  1.2925, -1.5285]]) torch.Size([1, 3])
b: tensor([[[ 1.0161,  1.2925, -1.5285]]]) torch.Size([1, 1, 3])
c: tensor([[[ 1.0161,  1.2925, -1.5285]]]) torch.Size([1, 1, 3])
f: tensor([ 0.7588, -1.0703, -1.2475]) torch.Size([3])
g: tensor([[ 0.7588, -1.0703, -1.2475]]) torch.Size([1, 3])


### Function 3 - * tensor.transpose() / tensor.permute()

In [7]:
# Example 1 - ### #transpose和permute()用來改變維度和順序
#transpose(input,dim0,dim1) 交換維度:dim0轉置的第一維 dim1轉置的第二維
#permute(dims) 有幾個維度，就要放幾個維度 dims(int...*):換位順序，必填
### your code ###
x = torch.randn(2, 3, 5)  #dim=0>>2,dim=1>>3,dim=2>>>5
print('x:',x,x.shape)

y=x.permute(2, 0, 1)
print('y:',y,y.shape)


x: tensor([[[-0.3964,  1.1006, -0.2972, -0.0502,  1.1749],
         [ 0.4525,  0.8143, -1.1211,  0.5842,  0.8114],
         [ 0.4373, -1.4728, -0.3661, -2.8344,  0.1130]],

        [[ 0.8026,  1.0318, -1.9001, -0.4998,  0.1752],
         [-0.2372,  1.2300,  3.1720,  1.4834, -0.3628],
         [-0.5284, -0.3564,  0.5845,  1.1801,  1.2744]]]) torch.Size([2, 3, 5])
y: tensor([[[-0.3964,  0.4525,  0.4373],
         [ 0.8026, -0.2372, -0.5284]],

        [[ 1.1006,  0.8143, -1.4728],
         [ 1.0318,  1.2300, -0.3564]],

        [[-0.2972, -1.1211, -0.3661],
         [-1.9001,  3.1720,  0.5845]],

        [[-0.0502,  0.5842, -2.8344],
         [-0.4998,  1.4834,  1.1801]],

        [[ 1.1749,  0.8114,  0.1130],
         [ 0.1752, -0.3628,  1.2744]]]) torch.Size([5, 2, 3])


In [31]:
# Example 2 -
### transpose()只能一次操作兩個維度，permute()可以一次操作多維數據
### your code ###
x=torch.randn(2,3) #shape[2,3]  dim0=2,dim1=3
print(x)
print(x.shape)
print('---------')
a=x.transpose(0,1) #shape[3,2]
print(a,a.shape)
print('----------')
b=x.transpose(1,0) #shape[3,2]
print(b,b.shape)
print('----------')
c=x.permute(0,1)   #shape[2,3]
print(c,c.shape)
print('---------') 
d=x.permute(1,0) #shape[3,2],不同於x.transpose(1,0)
print(d,d.shape)

#三維:
print('三維:')
x = torch.randn(2, 3, 5)  #dim=0>>2,dim=1>>3,dim=2>>>5
print('x:',x,x.shape) #shape[2,3,5]
e=x.transpose(0,1)
print(e,e.shape)     #shape[3,2,5]
print('---------')
f=y.transpose(0,2,1) #操作不了多維
print(f,f.shape)

tensor([[ 1.3159, -0.9301, -1.0125],
        [ 0.2634,  0.3707,  1.6328]])
torch.Size([2, 3])
---------
tensor([[ 1.3159,  0.2634],
        [-0.9301,  0.3707],
        [-1.0125,  1.6328]]) torch.Size([3, 2])
----------
tensor([[ 1.3159,  0.2634],
        [-0.9301,  0.3707],
        [-1.0125,  1.6328]]) torch.Size([3, 2])
----------
tensor([[ 1.3159, -0.9301, -1.0125],
        [ 0.2634,  0.3707,  1.6328]]) torch.Size([2, 3])
---------
tensor([[ 1.3159,  0.2634],
        [-0.9301,  0.3707],
        [-1.0125,  1.6328]]) torch.Size([3, 2])
三維:
x: tensor([[[-0.4155, -0.2898,  0.9228, -0.2653,  0.1043],
         [-0.2304, -2.4038,  0.0090, -1.8409, -0.8716],
         [-2.3199,  0.4588,  1.5132, -0.6685, -0.3104]],

        [[-0.3548, -0.6670, -0.4504, -1.2364, -2.1109],
         [ 0.7793,  0.4399,  0.1719,  0.3009, -0.6429],
         [-1.0658,  0.1947, -0.8230, -1.4220,  1.1711]]]) torch.Size([2, 3, 5])
tensor([[[-0.4155, -0.2898,  0.9228, -0.2653,  0.1043],
         [-0.3548, -0.6670, -0.45

TypeError: transpose() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (name dim0, name dim1)
 * (int dim0, int dim1)


In [26]:
y = torch.randn(2,3,4)
print(y,y.shape)
print("------------")

h=y.permute(0,2,1)
print(h,h.shape)
print('-----------')
j=y.permute(1,0,2)
print(j,j.shape)

tensor([[[ 0.1561,  1.0152, -0.2467, -2.2537],
         [ 0.5231, -0.3431,  1.8261,  0.2044],
         [ 0.2474, -0.9150, -0.9800, -0.4991]],

        [[-0.5262,  0.5815,  0.8542,  1.2622],
         [-1.1085, -1.2806, -0.3708, -0.5826],
         [-0.8704,  0.1808, -0.1720, -0.3412]]]) torch.Size([2, 3, 4])
------------
tensor([[[ 0.1561,  0.5231,  0.2474],
         [ 1.0152, -0.3431, -0.9150],
         [-0.2467,  1.8261, -0.9800],
         [-2.2537,  0.2044, -0.4991]],

        [[-0.5262, -1.1085, -0.8704],
         [ 0.5815, -1.2806,  0.1808],
         [ 0.8542, -0.3708, -0.1720],
         [ 1.2622, -0.5826, -0.3412]]]) torch.Size([2, 4, 3])
-----------
tensor([[[ 0.1561,  1.0152, -0.2467, -2.2537],
         [-0.5262,  0.5815,  0.8542,  1.2622]],

        [[ 0.5231, -0.3431,  1.8261,  0.2044],
         [-1.1085, -1.2806, -0.3708, -0.5826]],

        [[ 0.2474, -0.9150, -0.9800, -0.4991],
         [-0.8704,  0.1808, -0.1720, -0.3412]]]) torch.Size([3, 2, 4])


### Function 4 - * torch.reshape() / tensor.view()

In [29]:
# Example 1 - reshape和view都可以改變tensor的形狀，且兩者改變後的結果相同
### your code ###
a=torch.randint(low=0,high=10,size=(4,6))
print(a,a.shape)
print(' ')
b=a.reshape(8,3)
c=a.view(8,3)
print(b,b.shape)
print(' ')
print(c,c.shape)

tensor([[0, 3, 4, 5, 5, 5],
        [0, 8, 5, 2, 8, 1],
        [0, 7, 2, 5, 7, 2],
        [7, 4, 2, 1, 1, 2]]) torch.Size([4, 6])
 
tensor([[0, 3, 4],
        [5, 5, 5],
        [0, 8, 5],
        [2, 8, 1],
        [0, 7, 2],
        [5, 7, 2],
        [7, 4, 2],
        [1, 1, 2]]) torch.Size([8, 3])
 
tensor([[0, 3, 4],
        [5, 5, 5],
        [0, 8, 5],
        [2, 8, 1],
        [0, 7, 2],
        [5, 7, 2],
        [7, 4, 2],
        [1, 1, 2]]) torch.Size([8, 3])


In [31]:
# Example 2 - ### 
### your code ###
a=torch.randint(low=0,high=10,size=(4,6))
print(a,a.shape)
print(' ')
d=a.reshape(4,-1)
print(d,d.shape)
print(' ')
e=a.view(4,-1)
print(e,e.shape)

tensor([[8, 3, 9, 8, 3, 2],
        [5, 7, 9, 6, 8, 7],
        [7, 7, 6, 5, 5, 4],
        [6, 5, 1, 3, 9, 2]]) torch.Size([4, 6])
 
tensor([[8, 3, 9, 8, 3, 2],
        [5, 7, 9, 6, 8, 7],
        [7, 7, 6, 5, 5, 4],
        [6, 5, 1, 3, 9, 2]]) torch.Size([4, 6])
 
tensor([[8, 3, 9, 8, 3, 2],
        [5, 7, 9, 6, 8, 7],
        [7, 7, 6, 5, 5, 4],
        [6, 5, 1, 3, 9, 2]]) torch.Size([4, 6])
